#!/bin/sh
#
# Alfresco Tomcat startup
# Provided by https://github.com/andergrim/alfresco-freebsd-install
#
# PROVIDE: alfresco
# REQUIRE: DAEMON
# BEFORE: LOGIN
# KEYWORD: shutdown

export JAVA_HOME="/usr/local/openjdk7/"
export JRE_HOME=$JAVA_HOME/jre
export ALF_HOME="/opt/alfresco"
export CATALINA_HOME="$ALF_HOME/tomcat"
export CATALINA_PID="${ALF_HOME}/tomcat.pid"
export USER="alfresco"
export GROUP="www"

export LC_ALL=@@LOCALESUPPORT@@

# IMPORTANT Updated to match memory available on your server.
# For production, A server with at least 8G ram, and -Xmx6G is recommended. More is better!
export JAVA_OPTS="-Xms1G -Xmx2G -Xss1024k -XX:MaxPermSize=256m"

export JAVA_OPTS="${JAVA_OPTS} -Duser.country=US -Duser.region=US -Duser.language=en -Duser.timezone=\"Europe/Stockholm\" -d64"
#Enable this if you encounter problems with transformations of certain pdfs. Side effect is disable of remote debugging
#export JAVA_OPTS="${JAVA_OPTS}  -Djava.awt.headless=true"

#File encoding may be correct, but we specify them to be sure
export JAVA_OPTS="${JAVA_OPTS} -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8"
export JAVA_OPTS="${JAVA_OPTS} -Dalfresco.home=${ALF_HOME} -Dcom.sun.management.jmxremote=true"
export JAVA_OPTS="${JAVA_OPTS} -server"

. /etc/rc.subr

name="alfresco"
rcvar="alfresco_enable"
procname="java"
pidfile="$CATALINA_PID"

start_precmd="${name}_prestart"
start_cmd="${name}_start"

stop_precmd="${name}_prestop"
stop_cmd=":"
stop_postcmd="${name}_poststop"

alfresco_prestart()
{
  if [ ! -d "$ALF_HOME/logs" ]; then
    mkdir -p "$ALF_HOME/logs"
    chown -R $USER:$GROUP $ALF_HOME/logs
  fi

}

alfresco_start()
{
  cd $ALF_HOME/logs
  su -m ${USER} -c "${CATALINA_HOME}/bin/catalina.sh start"
}

alfresco_prestop()
{
  SHUTDOWN_PORT=`sockstat | grep 8005 | wc -l`
  if [ "$SHUTDOWN_PORT" -eq "0" ]; then
    echo "WARNING! Trying to shutdown before properly started. Waiting 120 seconds before stopping."
    sleep 120
    su -m ${USER} -c "${CATALINA_HOME}/bin/catalina.sh stop"
    sleep 10
  else
    su -m ${USER} -c "${CATALINA_HOME}/bin/catalina.sh stop"
    sleep 10
  fi
}

alfresco_poststop()
{
  rm -rf $CATALINA_HOME/temp/*
}

load_rc_config $name
run_rc_command "$1"
